# Generated by Django 2.1.15 on 2020-06-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soorder',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='soordergoods',
            options={'managed': False},
        ),
    ]
